### ISSUE TITLE
Saving app ID and secret key on my fresh Wordpress install results in warning messages

### ISSUE THREAD

**Issue by seanami** [intercom/intercom-wordpress#20]
I have a fresh Wordpress install (from the Dreamhost 1-click installer, which installs the latest version). When I install the Intercom plugin and save an app ID and secret key, I get these messages on the resulting page. The app ID and secret successfully save, but these messages make it look like something has gone wrong. I'd expect some sort of verification instead.

![screen shot 2015-09-21 at 11 54 39 am](https://cloud.githubusercontent.com/assets/330111/10001772/4b521c06-6058-11e5-9a53-4bbd16b7ab2e.png)

Let me know if additional details would be useful.

**Comment by bobjflong** [comment]
@seanami interesting thanks. No idea what this is tbh but investigating

**Comment by bobjflong** [comment]
Should be fixed in 1.0.2, can you try upgrade? Just delete and reinstall from the plugin dashboard should work if there's no upgrade button

**Comment by seanami** [comment]
Yep, that fixed it! Thanks Bob.
