### ISSUE TITLE
Are custom events supported?

### ISSUE THREAD

**Issue by jasonmcdermott** [intercom/intercom-wordpress#26]
Great plugin, just wondering if it's possible to add tracking for custom events?
thanks, J

**Comment by bobjflong** [comment]
Hi @jasonmcdermott - what kind of automation are you looking for? The plugin loads the Intercom Javascript, so something like this is possible right now:

```javascript
$(document).ready(function() {
  Intercom('trackEvent', 'invited-friend');
});
```

More here: http://docs.intercom.io/install-on-your-web-product/intercom-javascript-api
