### ISSUE TITLE
Opening IC via link

### ISSUE THREAD

**Issue by damiele** [intercom/intercom-wordpress#49]
Hi Bob,

thank you for your work.

I'm trying a simple "click here to contact me" that will open Intercom. I chatted with support and tried implementing:

window.intercomSettings = { 
"widget": { 
"activator": "#Intercom" 
}

in the bootstrap.php file (plus of course the #Intercom class in the HTML link) with no success.

Also I do not think that it would be a good idea for all future updates. Is this something that could be implemented in the plugin? I believe it is a vital function.

Thank you!
Daniele

**Comment by bobjflong** [comment]
Hi @damiele ,

Can you add extra CSS/JS to your WordPress site? If so - I'd recommend hiding the launcher using CSS, and then handling your contact link with javascript `Intercom('show')` which should pop open the messenger! https://docs.intercom.io/install-on-your-web-product/intercom-javascript-api

Let me know if I can help out!
