### ISSUE TITLE
Track more user data

### ISSUE THREAD

**Issue by Noxalus** [intercom/intercom-wordpress#52]
Hello everyone.

I use this plugin on Wordpress and I would like to track more data about users, data that could be provided by other plugins like WooCommerce for instance.

Do you know how I can do that easily with this plugin?

**Comment by damiele** [comment]
I'd like to add myself to the list, Intercom is a brilliant service, would love more features on this plugin.

Thanks.

**Comment by bobjflong** [comment]
Hi,

In lieu of adding lots of configuration I'd like to automatically track attributes that lots of users need. For example I did this with `ICL_LANGUAGE_CODE`: https://github.com/intercom/intercom-wordpress/pull/29

What kind of attributes would you like to see tracked automatically?

**Comment by Skaelv** [comment]
Hi,

When you get a better idea of which attributes you want to see tracked automatically you should definitely chat with the intercom support team.
They will forward your feature requests to the engineering team.
