### ISSUE TITLE
"Undefined index: _wpnonce" at wp-content/plugins/intercom/bootstrap.php:550

### ISSUE THREAD

**Issue by lkraav** [intercom/intercom-wordpress#61]
https://github.com/johnbillion/query-monitor helps detect these:

![screenshot from 2016-04-19 22-27-51](https://cloud.githubusercontent.com/assets/147228/14652669/fe22ac1c-067d-11e6-9503-387fdc975dc3.png)

**Comment by Skaelv** [comment]
Thanks for reporting that. 
This should fix it.
https://github.com/intercom/intercom-wordpress/pull/62
