### ISSUE TITLE
Hide messenger from specific user roles?

### ISSUE THREAD

**Issue by freemanlafleur** [intercom/intercom-wordpress#67]
What's the best way to hide the messenger from specific user roles when logged in?

I read the documentation here: https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/customize-the-intercom-messenger-technical but do not know how to modify this for use with the wordpress plugin.

**Comment by Skaelv** [comment]
Starting from `v2.5.16` you can override the Intercom messenger parameters in your theme if you want to specify your own custom logic to show/hide the messenger : https://github.com/intercom/intercom-wordpress#pass-extra-parameters-to-the-intercom-messenger

**Comment by Skaelv** [comment]
I'll close the issue now. Please re-open if my message didn't help.
