### ISSUE TITLE
Add a way to pass extra parameters

### ISSUE THREAD

**Issue by allaire** [intercom/intercom-wordpress#74]
Hi @bobjflong,

I had to edit the plugin directly to be able to add `"hide_default_launcher" => true`, like this:

```
function add_intercom_snippet()
{
  $options = get_option('intercom');
  $snippet_settings = new SnippetSettings(
    array("app_id" => WordPressEscaper::escJS($options['app_id']), "hide_default_launcher" => true),
    WordPressEscaper::escJS($options['secret']),
    WordPressEscaper::escJS($options['secure_mode']),
    wp_get_current_user()
  );
  $snippet = new Snippet($snippet_settings);
  echo $snippet->html();
}
```

I think it would be a good idea to expose an array somehow to pass to intercom settings (custom launchers, hide default launcher, etc.). Thoughts?

**Comment by allaire** [comment]
@Skaelv Hi, just checking in if you think this is a good idea.

Thanks!

**Comment by monecchi** [comment]
Hey there @allaire. Nice approach! It is indeed a good idea. The current plugin lacks a few options in order to improve and extend the API usage.

I've just came across an older [Wordpress plugin](https://wordpress.org/plugins/intercom/) for Intercom which seems not to be working anymore, and it is not being supported by the developer also, but it has a few filters for setting up custom user attributes, enable/disable settings, define what pages to completely exclude the widget to appear etc...

I'd like to send to Intercom a few more data such as a user's /customer's telephone, neighborhood and a few other stuff that is not supported out of the box with the current plugin.

**Comment by allaire** [comment]
@monecchi Yup. I suppose we can manually install the Intercom widget without the plugin, and customize it as we wish, but adding a filter to pass extra_data shouldn't be too hard to implement.

**Comment by monecchi** [comment]
@allaire I agree 💯 %. I'll manage to make some enhancements and see if they're worth sharing. So far I've dropped the plugin in favor of a manually install. The nice thing about the plugin though is that it uses Intercom's **Access Token** method as it seems that the `APP ID` method will be deprecated in mid June this year.

**Comment by lkraav** [comment]
```
commit 5a6b597cbef1e5b9142de56cad343470d5f0cfc2
Author: leho <leho@kraav.com>
Date:   Thu Jul 14 17:57:59 2016 +0300

    Add ability to filter intercomSettings

diff --git a/bootstrap.php b/bootstrap.php
index 0f499d8..48df80c 100644
--- a/bootstrap.php
+++ b/bootstrap.php
@@ -381,7 +381,7 @@ class SnippetSettings
 
   public function json()
   {
-    return json_encode($this->getRawData());
+    return json_encode(apply_filters("intercom_settings", $this->getRawData()));
   }
 
   public function appId()
```

Is there anything else needed?

**Comment by allaire** [comment]
@lkraav Thanks!

**Comment by lkraav** [comment]
@allaire I don't have merge permissions. Hopefully maintainers come around to this so we don't need to run custom patched versions.

**Comment by Skaelv** [comment]
Just released 2.5.16 which should allow you to use add_filter in your theme.

**Comment by pribilinskiy** [comment]
@lkraav, @Skaelv how can I [send UTM parameters](https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/track-conversions-and-clicks-with-utm-parameters) that are stored in cookies with a WP filter?

Following code will obviously not work ))

```php
add_filter('intercom_settings', function ($settings) {

	$settings['utm_source'] = $.cookie('utm_source');
	$settings['utm_medium'] = $.cookie('utm_source');
	$settings['utm_campaign'] = $.cookie('utm_source');

	return $settings;

});
```

**Comment by lkraav** [comment]
> how can I send UTM parameters that are stored in cookies with a WP filter?

@pribilinskiy how about trying `$_COOKIE`, the standard PHP cookie variable? Did you google at all? Why would you use JS notation inside PHP?

**Comment by pribilinskiy** [comment]
@lkraav haha, yes, I google every day since it's invention.
It was a sarcastic code, but you didn't get it

**Comment by lkraav** [comment]
True, I didn't get it. Still don't get where the opportunity for comedy even came about..

**Comment by pribilinskiy** [comment]
You're right, sarcastic is not the right word here, better to say imaginary for one who knows both PHP and JS
