### ISSUE TITLE
Changing user e-mail in WP creates a new Intercom user

### ISSUE THREAD

**Issue by lkraav** [intercom/intercom-wordpress#89]
May I inquire what is the rational for not using `user_id` with matching WP user id?

We have use cases where customers have legimate reasons for changing their account e-mail addresses and this messes up their tags, their message targeting etc.

https://github.com/intercom/intercom-wordpress/issues/74 would make it trivial for everyone to fix their one use cases, so two hands up for solving that issue.

Your thoughts?

**Comment by Skaelv** [comment]
The reason why we do not match Wordpress `user_id` with Intercom `user_id` is that it could potentially conflict with other integrations doing the same thing. We realized it's generally a bad practice to try to use user_id as a unique identifier.
[Your fix](https://github.com/intercom/intercom-wordpress/pull/90) should allow you to do so if you are confident you are not updating users user_id in another workflow.
